services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'todo-user'
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_DB: 'todo'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'